<?php
/*
 * Copyright (c) 2023 DPO Group
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

$formData = $this->getFormData();
?>
<h2><?php
    echo $this->escapeHtml($this->getMessage()); ?></h2>

<form name="<?php
echo $this->escapeHtml($this->getName()); ?>"
      id="<?php
      echo $this->escapeHtml($this->getId()); ?>"
      action="<?php
      echo $this->escapeHtml($formData["payUrl"]); ?>"
      method="get">
    <input type="hidden" name="ID" value="<?php
    echo $this->escapeHtml($formData["ID"]); ?>">
</form>
<script type="text/javascript">document.getElementById('dpo_checkout').submit()</script>
