<?php

/*
 * Copyright (c) 2024 DPO Group
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<?php
if ($instructions = $block->getMethod()->getInstructions()) { ?>
    <div class="items <?=
    $block->escapeHtml(getMethodCode()) ?> instructions agreement content" id="payment_form_<?=
    $block->escapeHtml(getMethodCode()) ?>" style="display: none;">
        <?=
        $block->escapeHtml(nl2br($instructions)) ?>
    </div>
    <?php
} ?>
