<?php
/** @noinspection PhpUndefinedVariableInspection */

/*
 * Copyright (c) 2023 DPO Group
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<?php
if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?php
    echo $block->getMethodCode() ?> instructions agreement content" id="payment_form_<?php
    echo $block->getMethodCode() ?>" style="display: none;">
        <?php
        echo nl2br($block->escapeHtml($instructions)) ?>
    </div>
<?php
endif; ?>
